[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  NPM_FLAGS = "--legacy-peer-deps"

# Optimize build performance
[build.processing]
  skip_processing = false

# Handle large files better
[build.processing.images]
  compress = true
